### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by macMikey** [miyako/tree-sitter-4dxml#1]
Installing “tree-sitter-4dxml@0.3.0” failed.Hide output…
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/Users/me/.atom/packages/tree-sitter-4dxml/node_modules/npm/node_modules/set-blocking/CHANGELOG.md'
Emitted 'error' event at:
    at WriteStream.onerror (_stream_readable.js:696:12)
    at WriteStream.emit (events.js:182:13)
    at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:211:14
    at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:241:16
    at FSReqWrap.oncomplete (fs.js:169:20)

**Comment by miyako** [comment]
what are you trying to do? 

stop spamming please.

**Comment by macMikey** [comment]
1.47.0
I'm trying to install the 4D packages that appear in the package manager.
<img width="1200" alt="Screen Shot 2020-06-01 at 13 45 05" src="https://user-images.githubusercontent.com/10867016/83437887-8967cc80-a40e-11ea-9828-4e7d6f41c48c.png">

**Comment by miyako** [comment]
Does Atom have "Full Disk Access" ?

**Comment by miyako** [comment]
<img width="668" alt="Screen Shot 2020-06-02 at 3 12 44" src="https://user-images.githubusercontent.com/1725068/83439900-f2872880-a47e-11ea-925c-ce224b2dffe1.png">

**Comment by miyako** [comment]
see 

https://flight-manual.atom.io/faq/sections/why-does-macos-say-that-atom-wants-to-access-my-calendar-contacts-photos-etc/

**Comment by macMikey** [comment]
on mine, atom only wanted files and folders.  i'll add full disk.
<img width="592" alt="Screen Shot 2020-06-01 at 14 26 21" src="https://user-images.githubusercontent.com/10867016/83441171-17928180-a414-11ea-9284-a10f783c3581.png">
<img width="601" alt="Screen Shot 2020-06-01 at 14 26 07" src="https://user-images.githubusercontent.com/10867016/83441185-1cefcc00-a414-11ea-96e5-927876155ee1.png">

**Comment by macMikey** [comment]
closing per the others - adding full disk fixed.
