### ISSUE TITLE
I've cloned the repo and. There is something I'm missing?

### ISSUE THREAD

**Issue by fesnavarro** [miyako/tree-sitter-4dxml#2]
I also config treesitter in:
parser_config.xml = {
  install_info = {
    url = "https://github.com/miyako/tree-sitter-4dxml",
    files = {"src/parser.c"},
    -- optional entries:
    branch = "master", -- default branch in case of git repo if different from master
    generate_requires_npm = true, -- if stand-alone parser without npm dependencies
    requires_generate_from_grammar = true, -- if folder contains pre-generated src/parser.c
  },
  filetype = "xml",
}
After that opening a xml file I get the error. 
Error executing vim.schedule lua callback: Failed to load parser: uv_dlopen: /home/user/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/xml.so: undefined symbol: tree_sitter_fourdxml_external_scann
er_create
stack traceback:
        [C]: in function '_ts_add_language'
        /usr/share/nvim/runtime/lua/vim/treesitter/language.lua:35: in function 'require_language'
        /usr/share/nvim/runtime/lua/vim/treesitter.lua:39: in function '_create_parser'
        /usr/share/nvim/runtime/lua/vim/treesitter.lua:98: in function 'get_parser'
        ...t/playground/lua/nvim-treesitter-playground/internal.lua:52: in function 'get_node_at_cursor'
        ...t/playground/lua/nvim-treesitter-playground/internal.lua:418: in function 'fn'
        ...tart/playground/lua/nvim-treesitter-playground/utils.lua:25: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>

**Comment by miyako** [comment]
I am not sure I understand the problem; what are you trying to do? 

there is no need to clone the project if you only want to use it. you can install a package directly in atom.

**Comment by fesnavarro** [comment]
> I am not sure I understand the problem; what are you trying to do?
> 
> there is no need to clone the project if you only want to use it. you can install a package directly in atom.

I didn't know this source only works with Atom. I was trying to implement it on Neovim.
